"""Generate club/static/theme-motion.css: registers the Сумерки/Рассвет tokens (@property) so a theme
switch animates, with timing that depends on direction. The transitions only exist while theme.js has
the .theme-shift class on <html> (set for one switch), so loading a page never animates the theme.

Sunrise (to dawn): the horizon brightens first and the light climbs to the zenith while the sun rises.
Sunset (to dusk): the zenith darkens first, the horizon keeps its glow longest, the sun sinks.
Frosted surfaces change in the middle of the move; text uses a steep curve so it spends little time
at mid-contrast. Re-run after adding a token to the dusk block in themes.css:
    python scripts/make_theme_motion.py
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
themes = (ROOT / 'club' / 'static' / 'themes.css').read_text()
block = themes[themes.index(':root[data-theme="dusk"]{'):]
block = block[:block.index('}')]
names = [n for n in re.findall(r'(--[a-z0-9-]+):', block) if n not in {'--radius-card', '--blur', '--sun'}]

SKY = ['--sky-4', '--sky-3', '--sky-2', '--sky-1', '--sky-0']          # horizon .. zenith
TEXT = {'--text', '--muted', '--faint', '--accent-ink', '--gold-ink', '--on-accent', '--on-accent-muted'}
SCENE = ('--sun-', '--ray', '--cloud', '--haze', '--band', '--rim', '--orb')
SUN_EASE = 'cubic-bezier(.45,0,.2,1)'


def timings(rising):
    sun = '--sun 3s ' + SUN_EASE
    items = [sun]
    for n in names:
        if n in SKY:
            i = SKY.index(n) if rising else len(SKY) - 1 - SKY.index(n)
            items.append(f'{n} 2.2s {SUN_EASE} {i * .2:.1f}s')
        elif n.startswith(SCENE):
            items.append(f'{n} 2.6s {SUN_EASE} {.15 if rising else .3}s')
        elif n in TEXT:
            items.append(f'{n} 1.6s cubic-bezier(.85,0,.15,1) .5s')
        else:
            items.append(f'{n} 1.8s ease-in-out .35s')
    return ','.join(items)


css = ['/* Generated by scripts/make_theme_motion.py. Theme tokens are registered so switching theme',
       '   animates: a sunrise to Рассвет, a sunset to Сумерки. Transitions apply only while <html> has',
       '   .theme-shift (one switch); a transition is taken from the destination theme, which is how each',
       '   direction gets its own timing. */',
       '@property --sun{syntax:"<number>";inherits:true;initial-value:0}']
css += [f'@property {n}{{syntax:"<color>";inherits:true;initial-value:transparent}}' for n in names]
css.append(f':root.theme-shift[data-glass][data-theme="dawn"]{{transition:{timings(True)}}}')
css.append(f':root.theme-shift[data-glass][data-theme="dusk"]{{transition:{timings(False)}}}')
css.append('@media (prefers-reduced-motion:reduce){:root.theme-shift[data-glass][data-theme]{transition:none}}')
(ROOT / 'club' / 'static' / 'theme-motion.css').write_text('\n'.join(css) + '\n')
print(f'{len(names)} tokens registered')
