"""Generate club/static/theme-motion.css: registers the Сумерки/Рассвет tokens (@property) so a theme
switch animates, with timing that depends on direction. The transitions only exist while theme.js has
the .theme-shift class on <html> (set for one switch), so loading a page never animates the theme.

Sunrise (to dawn): the horizon brightens first and the light climbs to the zenith while the sun rises.
Sunset (to dusk): the zenith darkens first, the horizon keeps its glow longest, the sun sinks.
Frosted surfaces change in the middle of the move; text uses a steep curve so it spends little time
at mid-contrast. Re-run after adding a token to the dusk block in themes.css:
    python scripts/make_theme_motion.py
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
themes = (ROOT / 'club' / 'static' / 'themes.css').read_text()
block = themes[themes.index(':root[data-theme="dusk"]{'):]
block = block[:block.index('}')]
names = [n for n in re.findall(r'(--[a-z0-9-]+):', block) if n not in {'--radius-card', '--blur', '--sun'}]

SKY = ['--sky-4', '--sky-3', '--sky-2', '--sky-1', '--sky-0']          # horizon .. zenith
TEXT = {'--text', '--muted', '--faint', '--accent-ink', '--gold-ink', '--on-accent', '--on-accent-muted'}
SCENE = ('--sun-', '--ray', '--cloud', '--haze', '--band', '--rim', '--orb')
SUN_EASE = 'cubic-bezier(.45,0,.2,1)'


def timings(rising):
    sun = '--sun 3s ' + SUN_EASE
    items = [sun]
    for n in names:
        if n in SKY:
            i = SKY.index(n) if rising else len(SKY) - 1 - SKY.index(n)
            items.append(f'{n} 2.2s {SUN_EASE} {i * .2:.1f}s')
        elif n.startswith(SCENE):
            items.append(f'{n} 2.6s {SUN_EASE} {.15 if rising else .3}s')
        elif n in TEXT:
            items.append(f'{n} 1.6s cubic-bezier(.85,0,.15,1) .5s')
        else:
            items.append(f'{n} 1.8s ease-in-out .35s')
    return ','.join(items)


css = ['/* Generated by scripts/make_theme_motion.py. Theme tokens are registered so switching theme',
       '   animates: a sunrise to Рассвет, a sunset to Сумерки. Transitions apply only while <html> has',
       '   .theme-shift (one switch); a transition is taken from the destination theme, which is how each',
       '   direction gets its own timing. */',
       '@property --sun{syntax:"<number>";inherits:true;initial-value:0}']
css += [f'@property {n}{{syntax:"<color>";inherits:true;initial-value:transparent}}' for n in names]
css.append(f':root.theme-shift[data-glass][data-theme="dawn"]{{transition:{timings(True)}}}')
css.append(f':root.theme-shift[data-glass][data-theme="dusk"]{{transition:{timings(False)}}}')
# The skill map is the exception. Its few hundred nodes are composited layers, and repainting all of
# them on every frame of a 3 s colour change is what made the switch stutter there. Through a switch
# the map holds its colours (its own copy of the tokens, swapped in one step at the midpoint) and
# dips out and back in instead: an opacity fade the compositor runs without repainting anything.
MAP = '.tree-canvas'
HOLD, DIP = .9, 1.8
dawn_block = themes[themes.index(':root[data-theme="dawn"]{'):]
dawn_block = dawn_block[:dawn_block.index('}')]
values = {theme: dict(re.findall(r'(--[a-z0-9-]+):([^;]+)', text)) for theme, text in (('dusk', block), ('dawn', dawn_block))}
held = [n for n in names if n in values['dusk'] and n in values['dawn']]
for theme in ('dusk', 'dawn'):
    declarations = ';'.join(f'{n}:{values[theme][n]}' for n in held)
    steps = ','.join(f'{n} 0s linear {HOLD}s' for n in held)
    css.append(f':root.theme-shift[data-glass][data-theme="{theme}"] {MAP}{{{declarations};transition:{steps};animation:map-dip {DIP}s ease-in-out}}')
css.append('@keyframes map-dip{0%,100%{opacity:1}40%,60%{opacity:.08}}')

# Browsers with view transitions (theme.js adds .theme-fade instead of .theme-shift): animating ~70
# inherited tokens restyles and repaints the whole page every frame, which stutters. Instead the
# interface cross-fades from a snapshot of the old theme to the live new one (a GPU blend, nothing
# re-rendered per frame), and only the sky element animates its own tokens: the same sunrise or
# sunset, played by a handful of elements. A little quicker than the fallback.
FADE = .75
def sky_timings(rising):
    items = [f'--sun {3 * FADE:.2f}s {SUN_EASE}']
    for n in names:
        if n in SKY:
            i = SKY.index(n) if rising else len(SKY) - 1 - SKY.index(n)
            items.append(f'{n} {2.2 * FADE:.2f}s {SUN_EASE} {i * .2 * FADE:.2f}s')
        elif n.startswith(SCENE):
            items.append(f'{n} {2.6 * FADE:.2f}s {SUN_EASE} {(.15 if rising else .3) * FADE:.2f}s')
    return ','.join(items)
css.append(f':root.theme-fade[data-glass][data-theme="dawn"] .sky{{transition:{sky_timings(True)}}}')
css.append(f':root.theme-fade[data-glass][data-theme="dusk"] .sky{{transition:{sky_timings(False)}}}')
css.append(':root.theme-fade::view-transition-old(root),:root.theme-fade::view-transition-new(root){animation-duration:1.1s;animation-timing-function:cubic-bezier(.45,0,.25,1)}')
css.append('@media (prefers-reduced-motion:reduce){:root.theme-shift[data-glass][data-theme],:root.theme-shift[data-glass][data-theme] .tree-canvas{transition:none;animation:none}}')
(ROOT / 'club' / 'static' / 'theme-motion.css').write_text('\n'.join(css) + '\n')
print(f'{len(names)} tokens registered')
